// Code generated by mockery v2.14.0. DO NOT EDIT.

package depotpb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeDepotServiceServer is an autogenerated mock type for the UnsafeDepotServiceServer type
type MockUnsafeDepotServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedDepotServiceServer provides a mock function with given fields:
func (_m *MockUnsafeDepotServiceServer) mustEmbedUnimplementedDepotServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewMockUnsafeDepotServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUnsafeDepotServiceServer creates a new instance of MockUnsafeDepotServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUnsafeDepotServiceServer(t mockConstructorTestingTNewMockUnsafeDepotServiceServer) *MockUnsafeDepotServiceServer {
	mock := &MockUnsafeDepotServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
