// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"eda-in-golang/baskets/basketsclient/models"
)

// NewRemoveItemParams creates a new RemoveItemParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveItemParams() *RemoveItemParams {
	return &RemoveItemParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveItemParamsWithTimeout creates a new RemoveItemParams object
// with the ability to set a timeout on a request.
func NewRemoveItemParamsWithTimeout(timeout time.Duration) *RemoveItemParams {
	return &RemoveItemParams{
		timeout: timeout,
	}
}

// NewRemoveItemParamsWithContext creates a new RemoveItemParams object
// with the ability to set a context for a request.
func NewRemoveItemParamsWithContext(ctx context.Context) *RemoveItemParams {
	return &RemoveItemParams{
		Context: ctx,
	}
}

// NewRemoveItemParamsWithHTTPClient creates a new RemoveItemParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveItemParamsWithHTTPClient(client *http.Client) *RemoveItemParams {
	return &RemoveItemParams{
		HTTPClient: client,
	}
}

/* RemoveItemParams contains all the parameters to send to the API endpoint
   for the remove item operation.

   Typically these are written to a http.Request.
*/
type RemoveItemParams struct {

	// Body.
	Body *models.RemoveItemParamsBody

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveItemParams) WithDefaults() *RemoveItemParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveItemParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove item params
func (o *RemoveItemParams) WithTimeout(timeout time.Duration) *RemoveItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove item params
func (o *RemoveItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove item params
func (o *RemoveItemParams) WithContext(ctx context.Context) *RemoveItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove item params
func (o *RemoveItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove item params
func (o *RemoveItemParams) WithHTTPClient(client *http.Client) *RemoveItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove item params
func (o *RemoveItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the remove item params
func (o *RemoveItemParams) WithBody(body *models.RemoveItemParamsBody) *RemoveItemParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the remove item params
func (o *RemoveItemParams) SetBody(body *models.RemoveItemParamsBody) {
	o.Body = body
}

// WithID adds the id to the remove item params
func (o *RemoveItemParams) WithID(id string) *RemoveItemParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the remove item params
func (o *RemoveItemParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
