{
 "title": "Application",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Shopping Baskets Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(baskets_received_messages_count[$__rate_interval])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Shopping Baskets Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "increase(baskets_sent_messages_count[$__rate_interval])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Customers Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(customers_received_messages_count[$__rate_interval])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Customers Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "increase(customers_sent_messages_count[$__rate_interval])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Shopping Baskets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(baskets_baskets_started_count[$__rate_interval])",
     "legendFormat": "{{label_name}} Started"
    },
    {
     "expr": "increase(baskets_baskets_checked_out_count[$__rate_interval])",
     "legendFormat": "{{label_name}} Checked Out"
    },
    {
     "expr": "increase(baskets_baskets_canceled_count[$__rate_interval])",
     "legendFormat": "{{label_name}} Canceled"
    }
   ]
  },
  {
   "title": "Customers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(customers_customers_registered_count[$__rate_interval])",
     "legendFormat": "{{label_name}} Registrations"
    }
   ]
  },
  {
   "title": "Stores Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "increase(stores_sent_messages_count[$__rate_interval])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Create Order SEC Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(cosec_received_messages_count[$__rate_interval])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Create Order SEC Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(cosec_sent_messages_count[$__rate_interval])",
     "legendFormat": "{{message}}"
    }
   ]
  }
 ]
}