// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCustomerParams creates a new GetCustomerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCustomerParams() *GetCustomerParams {
	return &GetCustomerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomerParamsWithTimeout creates a new GetCustomerParams object
// with the ability to set a timeout on a request.
func NewGetCustomerParamsWithTimeout(timeout time.Duration) *GetCustomerParams {
	return &GetCustomerParams{
		timeout: timeout,
	}
}

// NewGetCustomerParamsWithContext creates a new GetCustomerParams object
// with the ability to set a context for a request.
func NewGetCustomerParamsWithContext(ctx context.Context) *GetCustomerParams {
	return &GetCustomerParams{
		Context: ctx,
	}
}

// NewGetCustomerParamsWithHTTPClient creates a new GetCustomerParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCustomerParamsWithHTTPClient(client *http.Client) *GetCustomerParams {
	return &GetCustomerParams{
		HTTPClient: client,
	}
}

/* GetCustomerParams contains all the parameters to send to the API endpoint
   for the get customer operation.

   Typically these are written to a http.Request.
*/
type GetCustomerParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get customer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomerParams) WithDefaults() *GetCustomerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get customer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get customer params
func (o *GetCustomerParams) WithTimeout(timeout time.Duration) *GetCustomerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get customer params
func (o *GetCustomerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get customer params
func (o *GetCustomerParams) WithContext(ctx context.Context) *GetCustomerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get customer params
func (o *GetCustomerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get customer params
func (o *GetCustomerParams) WithHTTPClient(client *http.Client) *GetCustomerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get customer params
func (o *GetCustomerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get customer params
func (o *GetCustomerParams) WithID(id string) *GetCustomerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get customer params
func (o *GetCustomerParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
