// Code generated by mockery v2.14.0. DO NOT EDIT.

package customerspb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeCustomersServiceServer is an autogenerated mock type for the UnsafeCustomersServiceServer type
type MockUnsafeCustomersServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedCustomersServiceServer provides a mock function with given fields:
func (_m *MockUnsafeCustomersServiceServer) mustEmbedUnimplementedCustomersServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewMockUnsafeCustomersServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUnsafeCustomersServiceServer creates a new instance of MockUnsafeCustomersServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUnsafeCustomersServiceServer(t mockConstructorTestingTNewMockUnsafeCustomersServiceServer) *MockUnsafeCustomersServiceServer {
	mock := &MockUnsafeCustomersServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
