// Code generated by mockery v2.14.0. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBasketRepository is an autogenerated mock type for the BasketRepository type
type MockBasketRepository struct {
	mock.Mock
}

// Load provides a mock function with given fields: ctx, basketID
func (_m *MockBasketRepository) Load(ctx context.Context, basketID string) (*Basket, error) {
	ret := _m.Called(ctx, basketID)

	var r0 *Basket
	if rf, ok := ret.Get(0).(func(context.Context, string) *Basket); ok {
		r0 = rf(ctx, basketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Basket)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, basketID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, basket
func (_m *MockBasketRepository) Save(ctx context.Context, basket *Basket) error {
	ret := _m.Called(ctx, basket)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Basket) error); ok {
		r0 = rf(ctx, basket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockBasketRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockBasketRepository creates a new instance of MockBasketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockBasketRepository(t mockConstructorTestingTNewMockBasketRepository) *MockBasketRepository {
	mock := &MockBasketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
