// Code generated by go-swagger; DO NOT EDIT.

package store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"eda-in-golang/stores/storesclient/models"
)

// RebrandStoreReader is a Reader for the RebrandStore structure.
type RebrandStoreReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RebrandStoreReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRebrandStoreOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRebrandStoreDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRebrandStoreOK creates a RebrandStoreOK with default headers values
func NewRebrandStoreOK() *RebrandStoreOK {
	return &RebrandStoreOK{}
}

/* RebrandStoreOK describes a response with status code 200, with default header values.

A successful response.
*/
type RebrandStoreOK struct {
	Payload models.StorespbRebrandStoreResponse
}

func (o *RebrandStoreOK) Error() string {
	return fmt.Sprintf("[PUT /api/stores/{id}/rebrand][%d] rebrandStoreOK  %+v", 200, o.Payload)
}
func (o *RebrandStoreOK) GetPayload() models.StorespbRebrandStoreResponse {
	return o.Payload
}

func (o *RebrandStoreOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRebrandStoreDefault creates a RebrandStoreDefault with default headers values
func NewRebrandStoreDefault(code int) *RebrandStoreDefault {
	return &RebrandStoreDefault{
		_statusCode: code,
	}
}

/* RebrandStoreDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RebrandStoreDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the rebrand store default response
func (o *RebrandStoreDefault) Code() int {
	return o._statusCode
}

func (o *RebrandStoreDefault) Error() string {
	return fmt.Sprintf("[PUT /api/stores/{id}/rebrand][%d] rebrandStore default  %+v", o._statusCode, o.Payload)
}
func (o *RebrandStoreDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RebrandStoreDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
