// Code generated by go-swagger; DO NOT EDIT.

package basket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBasketParams creates a new GetBasketParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBasketParams() *GetBasketParams {
	return &GetBasketParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBasketParamsWithTimeout creates a new GetBasketParams object
// with the ability to set a timeout on a request.
func NewGetBasketParamsWithTimeout(timeout time.Duration) *GetBasketParams {
	return &GetBasketParams{
		timeout: timeout,
	}
}

// NewGetBasketParamsWithContext creates a new GetBasketParams object
// with the ability to set a context for a request.
func NewGetBasketParamsWithContext(ctx context.Context) *GetBasketParams {
	return &GetBasketParams{
		Context: ctx,
	}
}

// NewGetBasketParamsWithHTTPClient creates a new GetBasketParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBasketParamsWithHTTPClient(client *http.Client) *GetBasketParams {
	return &GetBasketParams{
		HTTPClient: client,
	}
}

/* GetBasketParams contains all the parameters to send to the API endpoint
   for the get basket operation.

   Typically these are written to a http.Request.
*/
type GetBasketParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get basket params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBasketParams) WithDefaults() *GetBasketParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get basket params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBasketParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get basket params
func (o *GetBasketParams) WithTimeout(timeout time.Duration) *GetBasketParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get basket params
func (o *GetBasketParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get basket params
func (o *GetBasketParams) WithContext(ctx context.Context) *GetBasketParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get basket params
func (o *GetBasketParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get basket params
func (o *GetBasketParams) WithHTTPClient(client *http.Client) *GetBasketParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get basket params
func (o *GetBasketParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get basket params
func (o *GetBasketParams) WithID(id string) *GetBasketParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get basket params
func (o *GetBasketParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetBasketParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
