// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorespbCreateStoreResponse storespb create store response
//
// swagger:model storespbCreateStoreResponse
type StorespbCreateStoreResponse struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this storespb create store response
func (m *StorespbCreateStoreResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storespb create store response based on context it is used
func (m *StorespbCreateStoreResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorespbCreateStoreResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorespbCreateStoreResponse) UnmarshalBinary(b []byte) error {
	var res StorespbCreateStoreResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
