// Code generated by mockery v2.14.0. DO NOT EDIT.

package storespb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeStoresServiceServer is an autogenerated mock type for the UnsafeStoresServiceServer type
type MockUnsafeStoresServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedStoresServiceServer provides a mock function with given fields:
func (_m *MockUnsafeStoresServiceServer) mustEmbedUnimplementedStoresServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewMockUnsafeStoresServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUnsafeStoresServiceServer creates a new instance of MockUnsafeStoresServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUnsafeStoresServiceServer(t mockConstructorTestingTNewMockUnsafeStoresServiceServer) *MockUnsafeStoresServiceServer {
	mock := &MockUnsafeStoresServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
