// Code generated by go-swagger; DO NOT EDIT.

package invoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPayInvoiceParams creates a new PayInvoiceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPayInvoiceParams() *PayInvoiceParams {
	return &PayInvoiceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPayInvoiceParamsWithTimeout creates a new PayInvoiceParams object
// with the ability to set a timeout on a request.
func NewPayInvoiceParamsWithTimeout(timeout time.Duration) *PayInvoiceParams {
	return &PayInvoiceParams{
		timeout: timeout,
	}
}

// NewPayInvoiceParamsWithContext creates a new PayInvoiceParams object
// with the ability to set a context for a request.
func NewPayInvoiceParamsWithContext(ctx context.Context) *PayInvoiceParams {
	return &PayInvoiceParams{
		Context: ctx,
	}
}

// NewPayInvoiceParamsWithHTTPClient creates a new PayInvoiceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPayInvoiceParamsWithHTTPClient(client *http.Client) *PayInvoiceParams {
	return &PayInvoiceParams{
		HTTPClient: client,
	}
}

/* PayInvoiceParams contains all the parameters to send to the API endpoint
   for the pay invoice operation.

   Typically these are written to a http.Request.
*/
type PayInvoiceParams struct {

	// Body.
	Body interface{}

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pay invoice params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PayInvoiceParams) WithDefaults() *PayInvoiceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pay invoice params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PayInvoiceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pay invoice params
func (o *PayInvoiceParams) WithTimeout(timeout time.Duration) *PayInvoiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pay invoice params
func (o *PayInvoiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pay invoice params
func (o *PayInvoiceParams) WithContext(ctx context.Context) *PayInvoiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pay invoice params
func (o *PayInvoiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pay invoice params
func (o *PayInvoiceParams) WithHTTPClient(client *http.Client) *PayInvoiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pay invoice params
func (o *PayInvoiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the pay invoice params
func (o *PayInvoiceParams) WithBody(body interface{}) *PayInvoiceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the pay invoice params
func (o *PayInvoiceParams) SetBody(body interface{}) {
	o.Body = body
}

// WithID adds the id to the pay invoice params
func (o *PayInvoiceParams) WithID(id string) *PayInvoiceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the pay invoice params
func (o *PayInvoiceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PayInvoiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
