// Code generated by go-swagger; DO NOT EDIT.

package basket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"eda-in-golang/baskets/basketsclient/models"
)

// StartBasketReader is a Reader for the StartBasket structure.
type StartBasketReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StartBasketReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStartBasketOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewStartBasketDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewStartBasketOK creates a StartBasketOK with default headers values
func NewStartBasketOK() *StartBasketOK {
	return &StartBasketOK{}
}

/* StartBasketOK describes a response with status code 200, with default header values.

A successful response.
*/
type StartBasketOK struct {
	Payload *models.BasketspbStartBasketResponse
}

func (o *StartBasketOK) Error() string {
	return fmt.Sprintf("[POST /api/baskets][%d] startBasketOK  %+v", 200, o.Payload)
}
func (o *StartBasketOK) GetPayload() *models.BasketspbStartBasketResponse {
	return o.Payload
}

func (o *StartBasketOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BasketspbStartBasketResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStartBasketDefault creates a StartBasketDefault with default headers values
func NewStartBasketDefault(code int) *StartBasketDefault {
	return &StartBasketDefault{
		_statusCode: code,
	}
}

/* StartBasketDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type StartBasketDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the start basket default response
func (o *StartBasketDefault) Code() int {
	return o._statusCode
}

func (o *StartBasketDefault) Error() string {
	return fmt.Sprintf("[POST /api/baskets][%d] startBasket default  %+v", o._statusCode, o.Payload)
}
func (o *StartBasketDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *StartBasketDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
